export const OUTDOOR_ICONS = [
    { name: 'snowboard' as const, label: 'Snowboard' },
    { name: 'grill' as const, label: 'BBQ' },
    { name: 'roller-skate' as const, label: 'Rollerblades' },
    { name: 'bike' as const, label: 'Bicycle' },
    { name: 'ski' as const, label: 'Ski' },
    { name: 'fish' as const, label: 'Fishing' },
    { name: 'hiking' as const, label: 'Hiking' },
    { name: 'kayaking' as const, label: 'Kayaking' },
    { name: 'surfing' as const, label: 'Surfing' },
    { name: 'golf' as const, label: 'Golf' },
    { name: 'tennis' as const, label: 'Tennis' },
    { name: 'basketball' as const, label: 'Basketball' },
    { name: 'soccer' as const, label: 'Soccer' },
    { name: 'volleyball' as const, label: 'Volleyball' },
    { name: 'tent' as const, label: 'Camping' },
    { name: 'hockey-puck' as const, label: 'Hockey' },
    { name: 'swim' as const, label: 'Swimming' },
    { name: 'run' as const, label: 'Running' },
    { name: 'yoga' as const, label: 'Yoga' },
    { name: 'weight' as const, label: 'Gym' },
    { name: 'dumbbell' as const, label: 'Fitness' },
    { name: 'snowflake' as const, label: 'Winter' },
    { name: 'weather-sunny' as const, label: "Summer" },
    { name: 'waves' as const, label: "Water" }
];
